### ISSUE TITLE
[Feat] 프로필 이름 설정을 구현합니다.

### ISSUE THREAD

**Issue by hsw1920** [hsw1920/Minsaeng#1]
### 작업에 대한 간단한 설명
- 최초 App 시작 시 ProfileSetting Flow의 프로필 이름 설정을 구현합니다.

### TODO
**커스텀 텍스트필드 구현**
- [x] 밑줄 progress 애니메이션 구현
- [x] placeholder 애니메이션 구현
- [x] touchDown, touchUp 시 애니메이션 구현

**커스텀 버튼 구현**
- [x] 활성화 여부에 따른 UI 변경 책임 구현

**VC**
- [x] 버튼의 appearing/hiding 애니메이션 구현
- [x] 진입 시 텍스트필드는 firstResponder

**Reactor**
- [x] 관련 ProfileNameCreationReactor 구현

### 작업 일정(Optional)
2024.04.15 - 2024.04.15

|작업일자|작업 내용|
|:---:|:---:|
|2024.04.15|UI 퍼블리싱 작업|
|2024.04.16|커스텀 컴포넌트의 리팩터링은 우선순위가 낮으므로 뒤로 미룸|
